import { GoogleGenAI } from '@google/genai';

const apiKey = typeof window !== 'undefined' 
  ? (import.meta.env?.VITE_GEMINI_API_KEY || '') 
  : '';

let aiClient: GoogleGenAI | null = null;
if (apiKey) {
  try {
    aiClient = new GoogleGenAI({ apiKey });
  } catch (err) {
    console.warn('Gemini client initialization warning:', err);
  }
}

export async function generateWorkerSubmission(taskTitle: string, taskDescription: string, isMalicious: boolean = false): Promise<string> {
  if (isMalicious) {
    return JSON.stringify({
      status: "MALICIOUS_SUBMISSION",
      quality: "POOR",
      content: "Lorem ipsum dolor sit amet. Unverified assertions: Sales will increase 10,000% without data. Corrupt sentiment index: #ERR_REF! Data missing for 90% of samples.",
      analysis: "Incomplete sample size. Random noise output generated by uncalibrated sub-node.",
      confidence: "38%"
    }, null, 2);
  }

  if (aiClient) {
    try {
      const response = await aiClient.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: `You are an elite Autonomous AI Worker Agent (InsightAI). Execute the following task and return a high-quality structured JSON report:
Task: ${taskTitle}
Description: ${taskDescription}

Provide comprehensive insights, sentiment analysis, key metrics, and actionable recommendations. Keep it concise yet thorough.`,
      });
      if (response.text) {
        return response.text;
      }
    } catch (err) {
      console.warn('Gemini API call failed, falling back to deterministic synthesis:', err);
    }
  }

  // Deterministic fallback report
  return JSON.stringify({
    task: taskTitle,
    executiveSummary: "Analysis of 1,500 customer feedback nodes reveals 78% positive sentiment, focused primarily on processing speed and transparent financial settlement.",
    keyMetrics: {
      totalFeedbackAnalyzed: 1500,
      positiveSentiment: "78.4%",
      netPromoterScoreEquivalent: "+62",
      primaryPainPoint: "Latency in legacy manual escrow approvals (Resolved by Autonomous Jury)"
    },
    clusters: [
      { category: "Settlement Speed", sentiment: 0.92, volume: 620, detail: "Users demand sub-second automated micro-settlement without human intervention." },
      { category: "Collateral Transparency", sentiment: 0.88, volume: 450, detail: "Skin-in-the-game collateral bonding increases task execution trust by 4.2x." },
      { category: "Jury Verifiability", sentiment: 0.85, volume: 430, detail: "Blind commit-reveal evaluation completely eliminates collusion vectors." }
    ],
    actionableRecommendations: [
      "1. Lock 10% worker collateral dynamically based on reputation risk score.",
      "2. Standardize 5-agent blind jury consensus with 80% pass threshold.",
      "3. Automate instant wallet credit upon jury consensus quorum."
    ],
    executionMetadata: {
      agent: "InsightAI (v3.4)",
      computeTimeMs: 412,
      accuracyScore: "95.4%"
    }
  }, null, 2);
}
